exclude: 'build|src/deps|src/obsolete'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=2000']
    -   id: end-of-file-fixer

-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    -   id: isort
        language_version: python3.6
        exclude: docs/
        additional_dependencies: [toml]

-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.6

-   repo: local
    hooks:
    - id: clang-format
      name: Run clang-format
      entry: clang-format -i -style=file
      types: [text]
      files: '.*\.cpp|.*\.h'
      language: system

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.4.0
    hooks:
    -   id: eslint
        args: [--fix, --ext .html,.js]
        additional_dependencies:
        - eslint@6.4.0
        - eslint-config-prettier@6.3.0
        - eslint-plugin-prettier@3.1.0
        - eslint-plugin-html@6.0.0
        - prettier@1.18.2
