exclude: '^(build|data/datasets|data/scene_datasets|node_modules/|src/deps|src/obsolete)'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=2000']
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
        # The JSONs below support comments (against spec)
        exclude: ^(.eslintrc.json|tsconfig.json)
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
        exclude: ^conda-build/habitat-sim/meta.yaml
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: requirements-txt-fixer

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: pretty-format-ini
        args: [--autofix]
    -   id: pretty-format-toml
        args: [--autofix]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        exclude: docs/

-   repo: https://github.com/ambv/black
    rev: 21.5b2
    hooks:
    - id: black
      exclude: ^examples/tutorials/(nb_python|colabs)

-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: ['--expand-star-imports', '--ignore-init-module-imports', '--in-place']
        exclude: docs/

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: docs/
        additional_dependencies:
        - flake8-bugbear==21.4.3
        - flake8-builtins==1.5.3
        - flake8-comprehensions==3.4.0
        - flake8-return==1.1.2
        - flake8-simplify==0.14.1

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    -   id: mypy
        pass_filenames: false

-   repo: https://github.com/seddonym/import-linter
    rev: v1.2.1
    hooks:
    -   id: import-linter

-   repo: https://github.com/kynan/nbstripout
    rev: 0.4.0
    hooks:
    -   id: nbstripout

-   repo: https://github.com/mwouts/jupytext
    rev: v1.11.2
    hooks:
    -   id: jupytext
        files: '^examples/tutorials/(colabs|nb_python)/(.*\.py|.*\.ipynb)$'
        args: [--update-metadata, '{"jupytext":{"notebook_metadata_filter":"all", "cell_metadata_filter":"-all"}, "accelerator":"GPU"}', --set-formats, 'nb_python//py:percent,colabs//ipynb,', --pipe, black, --pipe, 'isort - --treat-comment-as-code "# %%"', --pipe-fmt, 'py:percent', --sync]
        additional_dependencies:
            - 'nbformat<=5.0.8'
            - black
            - isort

-   repo: local
    hooks:
    - id: clang-format
      name: Run clang-format
      exclude: src/deps
      entry: clang-format -i -style=file
      types: [text]
      files: '.*\.(cpp|h|hpp|cu|cuh)$'
      language: system

-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
        exclude: (^src/(cmake/Find|deps)|configure\.h\.cmake$)

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.28.0
    hooks:
    -   id: eslint
        args: [--fix, --ext .html,.js]
        additional_dependencies:
        - eslint@6.4.0
        - eslint-config-prettier@6.3.0
        - eslint-plugin-prettier@3.1.0
        - eslint-plugin-html@6.0.0
        - prettier@1.18.2

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
    -   id: shellcheck
        exclude: ^conda-build/ #TODO fix these scripts

-   repo: https://github.com/AleksaC/circleci-cli-py
    rev: v0.1.15224
    hooks:
    -   id: circle-ci-validator
